name: sentry_dio
description: An integration which adds support for performance tracing for the Dio package.
version: 7.9.0
homepage: https://docs.sentry.io/platforms/dart/
repository: https://github.com/getsentry/sentry-dart
issue_tracker: https://github.com/getsentry/sentry-dart/issues
publish_to: none
documentation: https://docs.sentry.io/platforms/dart/configuration/integrations/dio/

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  dio: ^5.3.2
  sentry: 
    git: https://github.com/kumsumit/sentry.git

dev_dependencies:
  meta: ^1.10.0
  lints: ^2.1.1
  test: ^1.21.1
  coverage: ^1.3.0
  mockito: ^5.4.2
  yaml: ^3.1.0 # needed for version match (code and pubspec)
