name: sentry_dio
description: An integration which adds support for performance tracing for the Dio package.
version: 7.9.0
homepage: https://docs.sentry.io/platforms/dart/
repository: https://github.com/getsentry/sentry-dart
issue_tracker: https://github.com/getsentry/sentry-dart/issues
publish_to: none
documentation: https://docs.sentry.io/platforms/dart/configuration/integrations/dio/

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  dio: ^5.4.1
  sentry: 
    git: https://github.com/kumsumit/sentry.git

dev_dependencies:
  meta: ^1.11.0
  lints: ^3.0.0
  test: ^1.25.2
  coverage: ^1.7.2
  mockito: ^5.4.4
  yaml: ^3.1.2 # needed for version match (code and pubspec)
